#! /bin/sh
# SPDX-License-Identifier: BSD-3-Clause

# Test that libmptcpwrap injects MPTCP into the socket() system call.
#
# Copyright (c) 2021, Intel Corporation

set -e

LD_PRELOAD=../src/.libs/libmptcpwrap.so \
MPTCPWRAP_DEBUG=1 \
./mptcpwrap-tester
