#! /bin/sh
# SPDX-License-Identifier: BSD-3-Clause

# Test unknown command line option.
#
# Copyright (c) 2018-2019, 2021, Intel Corporation


../src/mptcpd --foo

# Command line usage error exit code.  See <sysexits.h>
EX_USAGE=64

# mptcpd should have exited with an EX_USAGE exit code.
test $? != $EX_USAGE
